"""empty message

Revision ID: 220a0eb1d360
Revises: 9be4fb3d3564
Create Date: 2020-04-10 11:34:33.618194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220a0eb1d360'
down_revision = '9be4fb3d3564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('members_user_fkey', 'members', type_='foreignkey')
    op.drop_constraint('members_board_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'])
    op.drop_column('members', 'user')
    op.drop_column('members', 'board')
    op.add_column('notes', sa.Column('board_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('member_id', sa.Integer(), nullable=True))
    op.drop_constraint('notes_board_fkey', 'notes', type_='foreignkey')
    op.drop_constraint('notes_member_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'members', ['member_id'], ['id'])
    op.drop_column('notes', 'member')
    op.drop_column('notes', 'board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('board', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('member', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_member_fkey', 'notes', 'members', ['member'], ['id'])
    op.create_foreign_key('notes_board_fkey', 'notes', 'boards', ['board'], ['id'])
    op.drop_column('notes', 'member_id')
    op.drop_column('notes', 'board_id')
    op.add_column('members', sa.Column('board', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_board_fkey', 'members', 'boards', ['board'], ['id'])
    op.create_foreign_key('members_user_fkey', 'members', 'users', ['user'], ['id'])
    op.drop_column('members', 'user_id')
    op.drop_column('members', 'board_id')
    # ### end Alembic commands ###
