"""empty message

Revision ID: 9be4fb3d3564
Revises: 522e78a91473
Create Date: 2020-04-10 11:27:51.104458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be4fb3d3564'
down_revision = '522e78a91473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boards_user_fkey', 'boards', type_='foreignkey')
    op.drop_column('boards', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('boards_user_fkey', 'boards', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
